### ISSUE TITLE
(From TPW2) Incompatibility at Heretic's End

### ISSUE THREAD

**Issue by Vectorial1024** [mewosmith/TeleportationWarsAlpha#5] opened 2019-10-29 08:13 UTC
The way to add a gate to Heretic's End back in TPW2 has caused incompatibility with other mods that also add gates to Heretic's End.

Known mods that add gates to Heretic's End are:

- XPANed Sectors (https://www.nexusmods.com/x4foundations/mods/334/)
- X Universe + (https://steamcommunity.com/sharedfiles/filedetails/?id=1780035703)

### How it had been incompatible

The zone definitions for Heretic's End contain no `connections` node. To add content to the zones in HE, a `connections` node must be generated via patching.

Currently, many mods opt to do "single-patch patching", and that is to directly add content under `connections\connection\*`. This will result in the following zone definition:

```
(Only part of the zone definition is shown for clarity)
/zone
    /connections (added by mod 1)
        /connection/*
    /connections (added by mod 2)
        /connection/*
    /connections (added by mod 3)
        /connection/*
```

Since there should only be 1 `connections` node, by referring to the load order, only 1 of the above 3 `connections` node (most likely the one that comes first) will be adopted by the game and considered as the "proper" `connections` node. And hence, only 1 of the 3 loaded mods will be "effective", so to speak.

### How it may be improved

The patch operations should be split into two:

- First patch adds an empty node `connections` under `zone`
- Second patch adds in content under the **1st `connections` node of the zone**

I will show that this indeed provides compatibility.

#### Case 1: this mod is the only mod loaded.

The game carries out the first patch, and now the zone definition is:

```
/zone
    /connections
```

Then, when the game carries out the second patch, since there is only 1 `connections` node, the new contents will be inserted in the only `connections` node, like this:

```
/zone
    /connections
        /connection/*
```

This is perfectly fine!

#### Case 2: There are other mods loaded together with this mod

Let's say there is exactly 1 other mod, which also modifies Heretic's End, loaded together with this mod. (The general case of N other mods can be reduced to this 1 other mod case due to mod load order, as explained above.)

Then the zone definition will look like this:

```
/zone
    /connections (added by the other mod)
        /connection/* (added by the other mod)
```

After the first patch, the definition will look like this:

```
/zone
    /connections (added by the other mod)
        /connection/* (added by the other mod)
    /connections (added by this mod)
```

When the second patch is executed, the "1st `connections` node" actually points to the `connections` node added by the other mod! So in the end, the definition will look like this:

```
/zone
    /connections (added by the other mod)
        /connection/* (added by the other mod)
        /connection/* (added by this mod)
    /connections (added by this mod)
```

And so when the game loads, both other mod's content and this mod's content are loaded and effective. It is also fine.

Therefore, I have shown that my proposed suggestion is compatible.

**Comment by mewosmith** [comment] 2019-10-29 13:32
This is by design.  A design that TPWAR 3 shares. Basically, TPWAR 2 was the first space mod for x4, and at the time other modders in the community felt that the "real" aspects of ship production should be preserved.  People are welcome to make compatibility patches.

I'm closing this as TPWAR 2 is unsupported and the issue is intended behaviour.

**Closed as completed by mewosmith** 2019-10-29 13:32 UTC
